chore: give a clearer message when `nurl` cannot be found
I naively tried building and running this with cargo, and ran into this
pretty useless error message:

```console
cargo build && ./target/debug/nix-init -u https://github.com/SatAgro/suntime
   Compiling nix-init v0.3.6 (/home/jeremy/src/github.com/nix-community/nix-init)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 5.94s
Error: No such file or directory (os error 2)
```

With this change, we get a much more useful message:

```console
cargo build && ./target/debug/nix-init -u https://github.com/SatAgro/suntime
   Compiling nix-init v0.3.6 (/home/jeremy/src/github.com/nix-community/nix-init)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 5.79s
Error: failed to run nurl

Caused by:
    No such file or directory (os error 2)
```

The "real" issue here is that I didn't have `nurl` on my `PATH`, because the
`full` devShell doesn't include it (this seems like a bug, I'll fix it
in a followup PR). However, I do think it's a kindness to give a
clearer error message here.